name: {{ env.IG_NAME }}
folder_id: {{ env.YC_FOLDER_ID }}
service_account_id: {{ env.YC_SERVICE_ACCOUNT_ID }}
description: Instance Group for {{ env.APP_NAME }}
instance_template:
  platform_id: standard-v2
  service_account_id: {{ env.YC_SERVICE_ACCOUNT_ID }}
  resources_spec:
    cores: 2
    memory: 4294967296
  boot_disk_spec:
    mode: READ_WRITE
    disk_spec:
      # Container Optimized Image (COI) - стандартный пользователь: yc-user
      image_id: fd846fg1abf9s6degc97
      type_id: network-hdd
      size: 21474836480
  network_interface_specs:
    - network_id: {{ env.YC_NETWORK_ID }}
      subnet_ids:
        - {{ env.YC_SUBNET_ID }}
      # primary_v4_address_spec обязателен (даже если пустой)
      # Если нужен публичный IP для SSH, раскомментируйте one_to_one_nat_spec:
      primary_v4_address_spec: {}
      # Публичный IP для SSH доступа (опционально):
      # primary_v4_address_spec:
        one_to_one_nat_spec:
          ip_version: IPV4
  metadata:
    # SSH ключ для доступа к инстансам
    # Формат: "yc-user:{{ env.SSH_PUBLIC_KEY }}"
    # Убедитесь, что добавили SSH_PUBLIC_KEY в GitHub Secrets
    ssh-keys: "yc-user:{{ env.SSH_PUBLIC_KEY }}"
  labels:
    app: {{ env.APP_NAME }}
scale_policy:
  fixed_scale:
    size: 2
allocation_policy:
  zones:
    - zone_id: ru-central1-a
deploy_policy:
  max_unavailable: 1
  max_expansion: 1
  max_deleting: 1
  max_creating: 1
  startup_duration: 120s

