name: {{ env.APP_NAME }}-ig
folder_id: {{ secrets.YC_FOLDER_ID }}
service_account_id: {{ secrets.YC_SERVICE_ACCOUNT_ID }}
description: Instance Group for {{ env.APP_NAME }}
instance_template:
  platform_id: standard-v2
  resources_spec:
    cores: 2
    memory: 4294967296
  boot_disk_spec:
    mode: READ_WRITE
    disk_spec:
      image_id: fd8kdq6d0pfr0it8v133
      type_id: network-hdd
      size: 21474836480
  network_interface_specs:
    - network_id: {{ secrets.YC_NETWORK_ID }}
      subnet_ids:
        - {{ secrets.YC_SUBNET_ID }}
      primary_v4_address_spec: {}
  labels:
    app: {{ env.APP_NAME }}
scale_policy:
  fixed_scale:
    size: 2
allocation_policy:
  zones:
    - zone_id: ru-central1-a
deploy_policy:
  max_unavailable: 1
  max_expansion: 1
  max_deleting: 1
  max_creating: 1
  startup_duration: 60s
health_check_spec:
  interval: 10s
  timeout: 5s
  unhealthy_threshold: 3
  healthy_threshold: 2
  http_options:
    port: 3333
    path: /health

