#cloud-config
# User-data для Container Optimized Image
# Подробнее: https://cloud.yandex.ru/docs/compute/concepts/vm-metadata
#
# SSH ключи для доступа к VM
# Для Container Optimized Image используется пользователь yc-user
#
# ВАЖНО: Для Yandex Cloud user-data должен быть в формате cloud-init YAML
# SSH ключ подставляется автоматически из GitHub Secrets (SSH_PUBLIC_KEY)
#
# ПРИМЕЧАНИЕ: Container Optimized Image автоматически обрабатывает docker-compose
# из метаданных через daemon yc-container-daemon. Не нужно настраивать systemd unit вручную.
# Action yc-coi-deploy передает docker-compose.yaml в метаданные VM с ключом 'docker-compose'.
users:
  - name: yc-user
    ssh_authorized_keys:
      - SSH_PUBLIC_KEY_PLACEHOLDER

