#cloud-config
# User-data для Container Optimized Image
# Подробнее: https://cloud.yandex.ru/docs/compute/concepts/vm-metadata
#
# SSH ключи для доступа к VM
# Для Container Optimized Image используется пользователь yc-user
#
# ВАЖНО: Для Yandex Cloud user-data должен быть в формате cloud-init YAML
# SSH ключ подставляется автоматически из GitHub Secrets (SSH_PUBLIC_KEY)
users:
  - name: yc-user
    ssh_authorized_keys:
      - SSH_PUBLIC_KEY_PLACEHOLDER

