services:
  "2":
    build:
      context: .
      dockerfile: apps/2/Dockerfile
      target: ${DOCKER_TARGET:-development}
    container_name: "2"
    ports:
      - 3000:3000
    env_file:
      - apps/2/.env
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./apps/2
          target: /app/apps/2
        - action: sync
          path: ./packages
          target: /app/packages
