services:
  nestjs:
    build:
      context: ./nestjs-apps
      dockerfile: apps/nestjs/Dockerfile
      target: ${DOCKER_TARGET:-development}
    container_name: nestjs
    ports:
      - 3001:3001
    env_file:
      - nestjs-apps/apps/nestjs/.env
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./nestjs-apps/apps/nestjs
          target: /app/apps/nestjs
        - action: sync
          path: ./nestjs-apps/packages
          target: /app/packages
  react:
    build:
      context: ./vite-apps
      dockerfile: apps/react/Dockerfile
      target: ${DOCKER_TARGET:-development}
    container_name: react
    ports:
      - 80:80
    env_file:
      - vite-apps/apps/react/.env
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./vite-apps/apps/react
          target: /app/apps/react
        - action: sync
          path: ./vite-apps/packages
          target: /app/packages
  react-2:
    build:
      context: ./vite-apps
      dockerfile: apps/react-2/Dockerfile
      target: ${DOCKER_TARGET:-development}
    container_name: react-2
    ports:
      - 81:81
    env_file:
      - vite-apps/apps/react-2/.env
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./vite-apps/apps/react-2
          target: /app/apps/react-2
        - action: sync
          path: ./vite-apps/packages
          target: /app/packages
