packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/packages/*'

catalogs:
  shared:
    '@types/node': ^20.0.0
    typescript: ^6.0.3
  nest:
    '@nestia/core': 11.3.4
    '@nestia/fetcher': 11.3.4
    '@nestia/sdk': 11.3.4
    '@nestjs/cli': ^11.0.0
    '@nestjs/common': ^11.0.0
    '@nestjs/core': ^11.0.0
    '@nestjs/platform-express': ^11.0.0
    '@types/express': ^5.0.0
    nestia: 11.3.4
    reflect-metadata: ^0.1.13
    rxjs: ^7.8.0
    ts-loader: ^9.5.1
    ts-patch: ^4.0.1
    typia: 12.1.0
    webpack-node-externals: ^3.0.0
  vite:
    '@tanstack/react-query': ^5.101.4
    '@types/react': ^19.0.0
    '@types/react-dom': ^19.0.0
    '@vitejs/plugin-react': ^5.0.4
    react: ^19.1.1
    react-dom: ^19.1.1
    vite: ^7.3.1
