import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { getTsconfig, parseTsconfig } from "get-tsconfig";
import { findMonorepoRoot } from "./findMonorepoRoot";

const DEFAULT_TSCONFIG = "tsconfig.json";
const EFFECTIVE_NAME = "tsconfig.node-run.json";
const PATHS_TRANSFORM = "@ttsc/paths";

type TsconfigFile = {
  compilerOptions?: {
    plugins?: Array<{ transform?: string; [key: string]: unknown }>;
    rootDir?: string;
    paths?: Record<string, string[]>;
    [key: string]: unknown;
  };
  [key: string]: unknown;
};

function toPosix(p: string): string {
  return p.replace(/\\/g, "/");
}

/**
 * Fully resolve the app tsconfig via get-tsconfig, then force:
 * - rootDir = monorepo root (findMonorepoRoot)
 * - paths["@/*"] = "./src/*" (app-local only; other aliases stay as declared in the app config)
 * - plugins with the ttsc paths transform
 *
 * Writes tsconfig.node-run.json next to the original. Returns absolute path.
 */
export function writeEffectiveTsconfig(appCwd = process.cwd()): string {
  const cwd = path.resolve(appCwd);
  const baseRel = process.env.NODE_RUN_TSCONFIG ?? DEFAULT_TSCONFIG;
  const baseAbs = path.resolve(cwd, baseRel);

  if (!existsSync(baseAbs)) {
    throw new Error(`[node-run] tsconfig not found: ${baseAbs}`);
  }

  const baseDir = path.dirname(baseAbs);
  const resolved =
    getTsconfig(baseDir, path.basename(baseAbs)) ??
    ({ path: baseAbs, config: parseTsconfig(baseAbs) } as const);

  if (!resolved?.config) {
    throw new Error(`[node-run] get-tsconfig could not resolve ${baseAbs}`);
  }

  const config = structuredClone(resolved.config) as TsconfigFile;
  if (!config.compilerOptions) config.compilerOptions = {};

  const monorepoRoot = findMonorepoRoot(cwd);
  const rootDir = toPosix(path.relative(baseDir, monorepoRoot) || ".");
  config.compilerOptions.rootDir = rootDir;

  // Only auto-path: app-local @/ → src. Shared aliases (@monorepo/*, …) stay manual in app tsconfig.
  const existingPaths = { ...(config.compilerOptions.paths ?? {}) };
  existingPaths["@/*"] = ["./src/*"];
  config.compilerOptions.paths = existingPaths;

  // get-tsconfig drops ttsc-only plugins; always force @ttsc/paths for emit
  config.compilerOptions.plugins = [{ transform: PATHS_TRANSFORM }];

  const outPath = path.join(baseDir, EFFECTIVE_NAME);
  const body =
    `// AUTO-GENERATED by node-run. DO NOT EDIT.\n` +
    `// Edit ${path.basename(baseAbs)} instead - this file is overwritten on every build/dev.\n` +
    `${JSON.stringify(config, null, 2)}\n`;

  writeFileSync(outPath, body, "utf8");
  return outPath;
}
